export const GET_LOST_ANIMALS = 'GET_LOST_ANIMALS';
export const NEXT_PAGE = 'NEXT_PAGE';
export const PREVIOUS_PAGE = 'PREVIOUS_PAGE'; 
export const SHOW_MODAL = 'SHOW_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';
export const SAVE_LOCATION = 'SAVE_LOCATION';
export const SET_LOCATION = 'SET_LOCATION';
export const GET_USER_ANIMALS = 'GET_USER_ANIMALS';
export const GET_ANIMAL_LOCATIONS = 'GET_ANIMAL_LOCATIONS';
export const SET_SELECTED_LOCATION = 'SET_SELECTED_LOCATION';
export const GET_LOST_AREA = 'GET_LOST_AREA';
export const SET_MARKER_INFO = 'SET_MARKER_INFO';
export const SET_ANIMAL = 'SET_ANIMAL';
export const RESET_ANIMAL = 'RESET_ANIMAL';
export const DELETE_LOST  = 'DELETE_LOST';
export const DISABLE_MARKER_INFO  = 'DISABLE_MARKER_INFO';

